### PR TITLE
Use node 0.10.41 as the base container to fix #76

### LINKED ISSUE #76: Containerized browserid-verifier uses more CPU than native one
I deployed a single tokenserver canary into production with the container. It appears that the CPU usage is much higher than the other production servers: 

high cpu

In stage testing it was the verifier container that was using up the bulk of the CPU. 

I suspect that this may be an issue that node4 requires a different compile flag for [browserid-crypto - usage](https://github.com/mozilla/browserid-crypto#usage)

### PR DESCRIPTION
**Pull request by mostlygeek**
- update circle.yml to add a version.json to the container
- update Dockerfile to use node 0.10.41 as the base container

### CODE REVIEW

**Comment by vladikoff** [comment]
@mostlygeek do you need this ASAP or should be investigate updating the versions in https://github.com/mozilla/browserid-verifier/issues/76#issuecomment-180573410

**Comment by mostlygeek** [comment]
@vladikoff when do you plan on merging your changes? It's not a blocker right now.

**Comment by vladikoff** [comment]
@mostlygeek I'll ask @rfk next week, if it is a lot of work then we will merge this early this week.

**Comment by jrgm** [comment]
I'm all for moving to node 4.x, but for purposes of establishing the use of docker, I'd keep the current 0.10 version, and see only what changes due to docker.

**Comment by vladikoff** [comment]
> I'm all for moving to node 4.x, but for purposes of establishing the use of docker, I'd keep the current 0.10 version, and see only what changes due to docker.

Okay agreed, let's give docker + 0.10 a try to avoid surprises there. then update once we have a new version of browserid-crypto

**Comment by mostlygeek** [comment]
Thanks. I tagged 0.3.2 to build a new container.

**Pull request merged**
