### PR TITLE
Add standard health-check endpints.

### LINKED ISSUE #93: Provide a /__version__ endpoint and return the current running version
Just like https://accounts.firefox.com/ver.json

cc @jbuck @jrgm

### PR DESCRIPTION
**Pull request by rfk**
Fixes #93; @jrgm r?

Logic shamelessly copied from fxa-auth-server.

### CODE REVIEW

**Comment by rfk** [comment]
Hrm, circle-ci failure suggests it's not picking up the version.json file, but I don't know how to debug that.

**Comment by jrgm** [comment]
Hey, I resemble that code. LGTM!

**Comment by vladikoff** [comment]
```

  1) health check __version__ should return version info:
     Uncaught AssertionError: expected 'unknown' to match /^[a-z0-9]{40}$/
      at Assertion.fail (node_modules/should/cjs/should.js:205:17)
      at Assertion.value (node_modules/should/cjs/should.js:277:19)
      at Request._callback (tests/health-check.js:61:27)
      at Request.self.callback (node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) health check __version__ should return version info (cached):
     Uncaught AssertionError: expected 'unknown' to match /^[a-z0-9]{40}$/
```

**Comment by vladikoff** [comment]
from mtg: need to check `version.json` in docker flow

**Comment by jrgm** [comment]
I will check that we actually create a version.json file as part of the docker build process.

**Comment by jrgm** [comment]
fixed the Docker build in circle.yml, but now I'm falling under required coverage. Huh?

**Comment by jrgm** [comment]
> but now I'm falling under required coverage. Huh?

I think I know why. If the version.json exists, lib/version.js short circuit returns an answer, dropping coverage numbers. I'll prove that's why and then change the tests to be runnable either with and without docker/circle.

**Comment by rfk** [comment]
Given the legacy status of this repo, I wouldn't feel too bad about just turning the test-coverage requirement down and/or annotating that new code to not be covered.

**Comment by jrgm** [comment]
I added a fix onto this branch that gets it to run correctly either under circleci or not (before I saw your above comment, Ryan). 

Circle tests are green now. r?

**Comment by rfk** [comment]
Nice 👍

**Pull request merged**
